### ISSUE TITLE
GUI for Woman Accept Factor?

### ISSUE THREAD

**Issue by guettli** [oniony/TMSU#104]
I like the command line. But a lot of users prefer a GUI.

Is nautilus or unity integration planed?

**Comment by oniony** [comment]
WTF, like seriously?

1. The title you have chosen is outright sexist. This is 2016, soon to be 2017, I don't think it even needs to be said: it's not acceptable.
2. There is a preexisting issue, #62, that covers this point already.
3. The [FAQ](https://github.com/oniony/TMSU/wiki/FAQ) already talks about this.

Fail.

**Comment by guettli** [comment]
The term WAF was not invented by me, altough the correct spelling is this: https://en.wikipedia.org/wiki/Wife_acceptance_factor

Do you know a better name for this topic: "Easy to use GUI" instead of "tool for geeks only"?

**Comment by oniony** [comment]
* The very link you sent above discusses the problems inherent with the term.
* The fact you used 'woman' rather than 'wife' makes it worse, as with the word 'wife' the suggestion is the partner is blocking a frivolous purchase whereas with 'woman' is suggests an inferiority of the sex.
* Just because you didn't invent the term doesn't mean you are absolved of responsibility in its use.

Irrespective of whether you think the terms is acceptable, you should please take due diligence in looking for preexisting issues and reading FAQs before raising issues in project trackers.
