### ISSUE TITLE
Change value of key-val tags without deleting and re-adding tag?

### ISSUE THREAD

**Issue by MaxPleaner** [oniony/TMSU#108]
When I create a key-val tag on a file, I want to be able to change the value later on. But this doesn't happen:

```txt
> touch test
> tmsu tag test foo=1
> tmsu tags test
foo=1
> tmsu tag test foo=2
> tmsu tags test
foo=1  foo=2
```

To avoid the duplicates, I have to untag it first:

```txt
> tmsu.untag test foo=1
> tmsu tag test foo=2
> tmsu tags foo
foo=2
```

**Comment by oniony** [comment]
That's by design. What if you have an `actor` tag and want to tag a movie
with two actors? Or an `artist` and want to tag an MP3 with two singers?
What if you have a `colour` tag and want to tag a piece of artwork with
multiple colours? Allowing only a single value would be very limiting.

As it stands you absolutely will need to untag once value before/after
tagging the second. I don't think it's with complicating the tool to handle
single value explicitly: after all, how often does one change the values
anyway?

**Comment by oniony** [comment]
Note also, that if you want to change a value everywhere, you can simply rename the value itself. For (annoying) example, when Victoria Adams got married, she became Victoria Beckham. You could update all uses of the value comme ca:

    tmsu rename --value Victoria_Adams Victoria_Beckham

(Note that you can actually use spaces in tag names if you're prepared to escape them.)

**Comment by MaxPleaner** [comment]
I'm making a Ruby program which wraps TMSU. I'm reflecting a file's tags in an in-memory dictionary which has unique keys. It's not a big deal to define 'update' as 'delete then create', I just didn't expect it.

It's a work in progress (doesn't quite work yet) but you can see [here](https://github.com/MaxPleaner/tmsu-rubY) if you're interested. 

And thanks for the codes.

**Comment by MaxPleaner** [comment]
@oniony is it possible to do a "scoped search" for files with a specific tag?

I.e. only searching in directory `./some/dir` and getting a list of paths.

**Comment by oniony** [comment]
Yes, there's the --path option.
