### ISSUE TITLE
Interface for Rapidly Tagging Many Small Files

### ISSUE THREAD

**Issue by TheChymera** [oniony/TMSU#124]
I'm looking to tag a large collection of images (though I assume the same issue would apply to small music or video files), and it would speed things up considerably if I could view and tag in a more seamless fashion. I would be looking for something like:

```
tmsu view-and-tag --viewer=eog *.{png,jpg,PNG,JPG}
```

which spawns e.g. the EOG viewer for the first file in the list, prints the file name to the terminal, and waits for me to input a list of tags (maybe with autocompletion) and then hit return - then kills the image viewer and proceeds to the next file.

I'm wondering whether:
* Something like this already exists
* You would be interested in shipping such a sub-command
* There exists some sort of precursor to this, on top of which I could create some shell script to provide the aforementioned functionality.
* There is any alternative approach to solving the issue at hand

**Comment by 0ion9** [comment]
I've implemented such a thing using [Lighthouse](https://github.com/emgram769/lighthouse), but it works in reverse (requires sxiv or some other viewer that lets you customize key-handling, typing a letter begins tagging, you can add as many space-separated tags as you want (or remove tags by beginning with -)). As usual for Lighthouse, it pops up a dialog you can type into, with completion results being shown as you type. Completion is eager rather than standard tab autocomplete(impossible with lighthouse) -- the tag most resembling the fragment you typed is selected for application.

It's somewhat complex, but usually works quite well.

**Comment by 0ion9** [comment]
Anyway for literally what you wrote, that can already be done with zsh:

```
vtag () {
  local viewer="$1"
  local tags
  local pid
  shift 1
  for V; do 
   "$viewer" "$V" &
   pid="$!"
   read "tags?Tags for $V: "
   kill "$pid"
   tmsu tag -t "$tags" -- "$V"
  done
}
```
No completion here.-- I'd probably move to Python to implement that. When implementing completion, I'd want to make sure tags that were already applied to the file were excluded.

A variant would use load all the images into the viewer at once, and use xdotool (if running under X rather than Wayland) to send keypresses to tell the image viewer to go to the next image. IMO that would achieve better flow, but depends on X and an image viewer supporting filelists (eg. sxiv, feh, geeqie)

The main problems in this paradigm are if a lot of tags are common between files [so you want to hit them all at once] or if you want to go back to a previous one. The flow I described in my previous reply addresses those by hooking things tighter into the image viewer -- apply tags to all marked files, navigate using image viewer..

A sort of middle ground would use the customizable actions that a range of image viewers support, invoking my Lighthouse-based script or (more modestly and directly comparable to the above snippet) a script wrapper around a Zenity text input dialog. I say middle ground because the tags still would not show in the viewer -- the only viewers where the statusline is customizable are AFAIK just sxiv and feh.

An in-viewer implementation is also possible in mpv and derivatives, via Lua. I haven't made much progress on implementing it, though. It may be possible to show tags via OSD or similar.

Another approach would be like GIMP's (show a dialog, with a widget per tag, click to remove, type more to add). IMO that kind of system only works for very small numbers of tags, although it is OK for adding tags.

I have otherwise not addressed removing tags, which IME is best doable at the same time as adding tags. the Lighthouse script I wrote opts to do this via a `-` prefix. If you do something like that then your script needs to parse the output to send one set to `tmsu tag` and the other to `tmsu untag`. As an example, my lhtag script achieves this with the following:

```
  ADD_TAGS=$(tr " " \\n <<< "$TAGSET"|egrep -v '^-' | tr \\n ' ' | sed -E 's/ +$//g')
  RM_TAGS=$(tr " " \\n <<< "$TAGSET"|egrep '^-'|sed -E 's/^-//g'| tr \\n ' ' | sed -E 's/ +$//g')
```
Where TAGSET is the set of tags returned by Lighthouse.

**Comment by TheChymera** [comment]
Hi again, I'm sorry, but I wasn't able to use the script. Either bash or zsh won't do anything after `./tagme.sh`. Could you explain how to use this?

**Comment by 0ion9** [comment]
It's just a function that you can throw in your .bashrc / .zshrc. It doesn't do anything until you invoke it (eg. `vtag sxiv *.png`). Personally, I would alias it, eg. `alias vt='vtag sxiv'`, and then use the alias.

**Comment by TheChymera** [comment]
I'm trying to use this in bash (ideally I would like to avoid installing `zsh` for this specifically), and I get:

```
[90] 13140
bash: read: `tags?Tags for png1_1280.jpg: ': not a valid identifier
tmsu: too few arguments
[10]   Terminated              "$viewer" "$V"
[31]   Terminated              "$viewer" "$V"
[39]   Terminated              "$viewer" "$V"
[41]   Terminated              "$viewer" "$V"
[48]   Terminated              "$viewer" "$V"
[50]   Terminated              "$viewer" "$V"
[51]   Terminated              "$viewer" "$V"
[52]   Terminated              "$viewer" "$V"
[53]   Terminated              "$viewer" "$V"
[54]   Terminated              "$viewer" "$V"
[55]   Terminated              "$viewer" "$V"
[56]   Terminated              "$viewer" "$V"
[57]   Terminated              "$viewer" "$V"
[58]   Terminated              "$viewer" "$V"
[59]   Terminated              "$viewer" "$V"
[60]   Terminated              "$viewer" "$V"
[61]   Terminated              "$viewer" "$V"
[62]   Terminated              "$viewer" "$V"
[63]   Terminated              "$viewer" "$V"
[64]   Terminated              "$viewer" "$V"
[65]   Terminated              "$viewer" "$V"
[66]   Terminated              "$viewer" "$V"
[67]   Terminated              "$viewer" "$V"
[68]   Terminated              "$viewer" "$V"
[69]   Terminated              "$viewer" "$V"
[70]   Terminated              "$viewer" "$V"
[71]   Terminated              "$viewer" "$V"
[72]   Terminated              "$viewer" "$V"
[73]   Terminated              "$viewer" "$V"
[74]   Terminated              "$viewer" "$V"
[75]   Terminated              "$viewer" "$V"
[76]   Terminated              "$viewer" "$V"
[77]   Terminated              "$viewer" "$V"
[78]   Terminated              "$viewer" "$V"
[79]   Terminated              "$viewer" "$V"
[80]   Terminated              "$viewer" "$V"
[81]   Terminated              "$viewer" "$V"
[82]   Terminated              "$viewer" "$V"
[83]   Terminated              "$viewer" "$V"
[84]   Terminated              "$viewer" "$V"
[85]   Terminated              "$viewer" "$V"
[86]   Terminated              "$viewer" "$V"
[87]   Terminated              "$viewer" "$V"
[88]   Terminated              "$viewer" "$V"
[89]   Terminated              "$viewer" "$V"
[90]+  Terminated              "$viewer" "$V"
```

**Comment by 0ion9** [comment]
Verified. This seems to be a difference in `read` builtin. For bash, the line should read `read -p "Tags for $V: " tags`.
With this change, it works in bash for me.

**Comment by TheChymera** [comment]
Yes, I am noticing there are quite a few differences for bash. Also, the window focus is switched to the inage viewer on every new image, etc. I am re-writing the script and will post it later today or tomorrow. To control the windows I need `wmctrl`. I guess it wouldn't be reasonable to distribute a script which depends on both `eog` an `wmctrl` with your software. I think it may be better if I make a separate scripts package for all these solutions.

**Comment by 0ion9** [comment]
> Also, the window focus is switched to the inage viewer on every new image

That's the responsibility of the WM, but yeah, to be expected by default.

I don't think a script that hardcodes viewer should be distributed, TBH (unless it exploits specific features of that particular viewer). But viewer doesn't have to be specified via argument. Another way is to read an environment var and provide a default, eg. `VIEWER="${VTAG_VIEWER:-eog}"`.

You can fall back wmctrl -> xdotool -> nothing
(eg '(wmctrl -a $WINID || xdotool windowactivate $WINID) 2>/dev/null 1>/dev/null`). That would make it much more distributable.
(obviously the 'nothing' option here would be more annoying, but that should just motivate people to install one of those packages.)

**Comment by TheChymera** [comment]
For createing the best experience (e.g. no stealing focus, being able to put the viewer in one place and have it stay there) I think it's unavoidable to use specific features. I think it's best to have one command per viewer, which optimally handles all of its associated idiosyncrasies.

I had neither `xdotool` nor `wmctrl` installed by default. Is there any reason to assume the former may be considerably more available? Anylway, would you pull in tmsoup?

**Comment by TheChymera** [comment]
This is my code:

```
eogtag () {
  WIN_ID=`wmctrl -l | cut -d ' ' -f1 | tail -n 1`
  for V in "$@"; do
    eog $V --single-window & disown
    sleep 0.8 &&
    wmctrl -i -a ${WIN_ID} &&
    echo "Type in TMSU tags:"
    read TAGS
    echo "Tagging ${V}"
    eval "tmsu tag ${V} ${TAGS}"
  done
}
```

Feel free to suggest improvements. The `sleep` line is important as there is some delay to EOG actually launching, and the `wmctrl` command needs to be executed after the EOG window is fully launched.

**Comment by 0ion9** [comment]
`eval "tmsu tag ${V} ${TAGS}"`

I'm not sure exactly what you are trying to do here, but I'm reasonably confident that this doesn't do what you think. The manner of quoting is also unsafe - eg. given filenames containing spaces, or tags that contain shell-special characters like *, $ or [
I'd suggest `tmsu tag -t "${TAGS}" -- "${V}"`.  This is safely quoted, and the use of -- makes filenames that happen to start with a `-` safe.
If you want to silence tmsu's output, eg 'new tag foo created', append `2>/dev/null`

You don't seem to ever kill eog instances. Why? I thought you had specified that as desirable originally.

` echo "Type in TMSU tags:"`
Suggest a trailing space to separate tag input from prompt

Also looking at this entire section:

```
sleep 0.8 &&
wmctrl -i -a ${WIN_ID} &&
echo "Type in TMSU tags:"
```
The value of && seems unclear. Don't you want to just sleep, then wmctrl, then echo?

If you want to only prompt the user for tags if both the sleep and wmctrl commands succeed (which is the implication of && here), you need to use a subshell or `if`. Currently, the prompt is conditionally printed, but the reading of tags and application of tags is unconditional.

eg.

```
if sleep 0.8 && wmctrl -i -a ${WIN_ID}; then 
  echo "Type in TMSU tags :"
  read TAGS
  echo "Tagging ${V}"
  tmsu tag -t "${TAGS}" -- "${V}" 1>/dev/null 2>/dev/null
fi
```

I'd be happy to pull it, once the outstanding issues are fixed.

**Comment by TheChymera** [comment]
Ok, looking into it. Are you sure `tmsu tag -t "${TAGS}" -- "${V}"` does what you said it does? It added a `--` tag to my list, which I am now having trouble removing :-/

**Comment by 0ion9** [comment]
F*ck. I remember doing that by accident too, but I thought that bug in TMSU's arg parsing was fixed.
([this issue](https://github.com/oniony/TMSU/issues/63) where I describe the bug also describes a way to use `sqlite3` to directly remove the `--` tag from tmsu db)

.. *tests*

Yes, it works. 
```
cd /tmp
tmsu init
touch foo
tmsu tag -t bar foo
tmsu tag -t baz -- foo
tmsu tags
```
(the two tags 'bar' and 'baz' are correctly shown.)

It probably means you are using an out-of-date TMSU, but I guess you would hardly be the only one, so probably `tmsu tag -t "${TAGS}" "${V}"` is the closest backward-compatible approximation.

**Comment by oniony** [comment]
Thanks @0ion9 for helping @TheChymera out with a solution to his requirements.

I don't think think the original request belongs in TMSU however: it would be up to supporting tools or scripts to do this. When, eventually, I rebuild TMSU to be more modular then it would be possible to build the core of TMSU into a graphical interface, rather than calling out to the TMSU binary.
