### ISSUE TITLE
Simplified Programmatic Access to Tags

### ISSUE THREAD

**Issue by martyg77** [oniony/TMSU#157]
When I pull the tags for an individual file in a bash script, tmsu automatically prefixes the filename into the output.  
```
$ touch file
$ tmsu tag file mark
$ tmsu tags file
mark
$echo $(tmsu tags file)
file: mark
```
My script requires the values only.  Running tmsu with output redirected will always prepend the filename. I cannot find a way to force tmsu to give me the tags without a filename inside a script, so I use this ugly filter to get the desired output
`tmsu tags -n "$1" | sed -e 's/^.*:[[:space:]]*//' | xargs echo -n
`
Perhaps a new option "tmsu tags -N" (Never print the filename) could be added to simplify the above.

How is everyone else getting around this issue?

**Comment by oniony** [comment]
Queries can return multiple files. If you have a script, it needs to have
consistent output, so TMSU always prepends the filename.

If you want to remove it, you could use sed or cut to get rid of it.

But you will still need to handle the possibility of there being multiple
files returned.

**Comment by martyg77** [comment]
I just want to query **one** file for its tags.

cut and sed is a mess, especially when taking under account escaped characters.
I provided a filter in my OP, which is my best 2 yr old working version.

Every time I look to simplify, e.g.
`tmsu tags -n "$1" | cut -c$((${#1}+3))- | xargs echo -n`
I run into corner case issues with escaped characters in the filename.

Just testing the waters to see if I am doing this the best way.
Sure would be nice not to have to jump though these hoops. :-)

Anyway, thanks for maintaining this very useful tool.

**Comment by oniony** [comment]
OK, I'll add a flag to suppress the filename.

**Comment by 0ion9** [comment]
OP doesn't handle escaped : in the filename and makes a few other unwarranted assumptions, so here is a small improvement:

`sed -Ee 's,^.+[^\]:[[:space:]]?(.*)$,\1,'`

Not sure why you strip the trailing newline; bash normally will ignore that AFAICS.

That said, assuming Oniony adds a flag to suppress the filename, you still need to cope with tags containing spaces, equals, or other special characters, spaces being the most pressing.

Here's some expressions handling those:
* `-e 's,([^\]) ,\1\n,g'` turns delimiters between tags or tag=value pairs into newlines rather than spaces. (this needs to be used before the below expressions)
* `-e  's,[^\]=,\t,g` turns the separator in a TAG=VALUE pair into a tab (this is unambiguous because TMSU doesn't allow tabs in tag or value names). 
* `-e 's,[\]([ =]),\1,g'` turns escaped spaces and equals within tags into literal spaces and equals.

Setting `IFS=$'\n'` (exactly) is also probably needed -- IIRC the default IFS includes tab.

**Comment by oniony** [comment]
I have modified the --name (-n) option to take an argument.

'auto', which is the default behaviour, will show the file/value name when there are multiple arguments or the output is not standard output. 'always' and 'never' are pretty self-explanatory.
