### ISSUE TITLE
Feature Request: have tags autocomplete

### ISSUE THREAD

**Issue by lbrunkho** [oniony/TMSU#158]
it would be really nice when adding, searching, or removing tags you could use the terminal auto complete to resolve names for existing tags in the current data base. This will help reduce mis-tagging by typing errors and speed up the process

**Comment by 0ion9** [comment]
*shell* auto-complete, not terminal. The distinction is important because each shell has their own way of implementing completions.

This functionality is implemented for zsh currently. I made an implementation for fish, which Paul asked to include but, as far as I can tell, has not done so.

You are probably using either bash (for which there is no completion, presently) or zsh. `echo $SHELL` will tell you what your shell is.

**Comment by lbrunkho** [comment]
I am using bash, but i guess i was drawing an example of the behaviour that I am looking for, I have also seen programs, ncftp comes to mind, that implement this functionality on there own, but my guess is that is very difficult to do and also restricts the ability for other programs to interact with it.
