### ISSUE TITLE
'tmsu untagged' returns potentially unwanted hidden files

### ISSUE THREAD

**Issue by ashleyharvey** [oniony/TMSU#162]
I'm running v. 0.7.4 on macOS (compiled from source); when I run tmsu untagged, I get among other things, .DS_Store, .fseventsd, .Trashes, .tmsu, etc.

Rather than running `tmsu untagged | grep -v "&^\.\/\."` to get rid of hidden files, which can be problematic when copying/moving/removing files among other things, it'd be nice to add in a flag to `tmsu untagged`; maybe `-h (--skip-hidden-files)`, to avoid the problem altogether.

**Comment by oniony** [comment]
Thanks for your suggestion and offer to help.

The best place to start, and what I typically do, is to look at other
mainstream Unix commands such as ls, find, &c. and see how they've tackled
the problem. Many times there are already conventions that can be followed
and it's better to do this as it's less jarring and less to remember for
the users if commands behave similarly.

As for implementation, we'll need to think about whether this should be an
option that affects every command (global option) or specific to a few
sub-commands such as "untagged" and "files".

Finally it'll be a case of adding the code. Now the thing to think about
here is that the tool can be used cross-platform so we can't just assume
that files that's name start with a period are hidden. On Windows, for
example, the hidden state is stored separately as file metadata flags so my
gut instinct is this functionality would need to sit in the CLI tier.

Alternatively we could store the hidden status in the database when the
file is added. On the plus side it means we could shunt the query logic
(filtering) down to the database tier where it's quicker and less prone to
error, but a massive drawback of this approach is that the TMSU state of
the file (whether it's hidden or not in the database) could be different to
the actual file on disk status. This means "repair" would then need to be
updated to fix these, and I feel the user experience may suffer. Plus we're
duplicating a lot of data that's already available, especially on Unix and
clones where it's already easy to infer the hidden status from the filename.

So my instinct is to apply this logic up at the CLI tier. (Or also suggests
I should have perhaps had a filesystem aware tier that between the CLI and
storage tiers, so that this functionality would be available to apps that
want to embed TMSU, but that's a bigger piece of work.)

So a lot to think about there.

**Comment by oniony** [comment]
OK, it would probably make sense for TMSU to ignore hidden files by default and that behaviour be overridable with either a flag or via a database setting. Personally I think the flag would be enough as a user could always alias the TMSU binary if they want the previous behaviour; I cannot conceive why a user would want different behaviours for different TMSU databases (and if it did transpire that they do then the database option could be added then). 

I think the regular expression idea is an unnecessary over-complication at this stage.

With regards to your dupes issue: please raise another ticket if you manage to identify how it is going wrong.

**Comment by ddombrowsky** [comment]
Why not a `.tmsuignore` file?

**Comment by ddombrowsky** [comment]
@ashleyharvey ok what happened here?  There are no changes in that closed PR.  Looks like `master` was force-pushed.  Is this implemented on master or no?

**Comment by ashleyharvey** [comment]
> @ashleyharvey ok what happened here? There are no changes in that closed PR. Looks like `master` was force-pushed. Is this implemented on master or no?

Honestly, my brain is spaghetti when it comes to git. I am not yet so familiar with it that I can do this well without getting myself into a mess. What had happened is I was working on an old code base, I decided to move my changes to a branch(after I had initially opened the PR), then I pushed my branch. Then. I realized my codebase was old, so I pulled, merged my changes into my master, and tried to re-push. You can imagine a git newbie doing all of that and the result was not good. This PR closed automatically when I force-pushed, so rather than trying to backtrack again and cause more of a problem, I just reset, brought my newest code changes in and resolved small conflicts with the latest codebase and checked in on another PR.

And, while enough of these experiences will help me learn how to deal with shared code cleanly, I'd love to hear what the normal work-flow is when dealing with stuff like this. I suppose to `git pull`, then merge the feature branch back into `master`, resolving conflicts locally, before pushing and opening a PR?

**Comment by ddombrowsky** [comment]
@ashleyharvey a typical work flow could be:
1. create a branch for a feature or bug fix (called the "topic" branch in some docs)
2. do the work
3. push the new branch to the repo (github in this case)
4. open a Pull Request (which is the same as a "Merge Request" in some other systems like gitlab) to merge it into the main branch (usually `master`).
5. review the code, and click merge, DONE.

It looks like you force-pushed the `master` branch, which shouldn't normally be done under any normal development workflow (unless you accidentally add sensitive files and need to remove them, for example).  If you started your work on old code, then you could either `git pull` to merge with current `origin/master`, or `git pull --rebase` to rebase the changes on top.  

What's the new PR that you created?

**Comment by ashleyharvey** [comment]
> @ashleyharvey a typical work flow could be:
> 
> 1. create a branch for a feature or bug fix (called the "topic" branch in some docs)
> 2. do the work
> 3. push the new branch to the repo (github in this case)
> 4. open a Pull Request (which is the same as a "Merge Request" in some other systems like gitlab) to merge it into the main branch (usually `master`).
> 5. review the code, and click merge, DONE.
> 
> It looks like you force-pushed the `master` branch, which shouldn't normally be done under any normal development workflow (unless you accidentally add sensitive files and need to remove them, for example). If you started your work on old code, then you could either `git pull` to merge with current `origin/master`, or `git pull --rebase` to rebase the changes on top.
> 
> What's the new PR that you created?

Thanks, this is really helpful.
Is there any need to merge my branch into my master before pushing? I read somewhere that that was normal and so that's what I tried to do after resetting. The only issue now is that if I make changes and push, it auto adds the commits to the PR, when I may only want to push up to my origin rather than upstream. I suppose I should just branch now for new features/changes and then not push those branches until I've pulled any new code first.

New PR: https://github.com/oniony/TMSU/pull/184

**Comment by ddombrowsky** [comment]
> Is there any need to merge my branch into my master before pushing?
If there is a chance that other things have been committed to `master`, then it might be useful to merge `master` into YOUR branch (which is the opposite of what you said).  However, for this repo, I don't think there would be enough activity to have to worry about that.

> The only issue now is that if I make changes and push, it auto adds the commits to the PR, 
Yes, new commits made to an open PR in github will automatically be added to the PR.  If you don't want this, you'd have to create a new branch.
