### ISSUE TITLE
Unwanted 'files' subdirectory in virtual filesystem within every tag directory

### ISSUE THREAD

**Issue by ykhurshid** [oniony/TMSU#164]
If I tag a file 'foo' with the tag 'bar', whenever I browse the "directory" representing 'bar' in the virtual file system, I see another subdirectory 'files' instead of just 'foo' which was what I expected it to be. The documentation suggests that this is unintended behaviour. 
Any tips on fixing this? I tried erasing and creating a new database to no avail.

**Comment by oniony** [comment]
'files' (under the 'tags' tree) is a special directory that evaluates the
chain of tags. TMSU did not used to have this directory: it used to work
how you imagined with all your files tagged 'foo' as soft links in the
'foo' subdirectory.

However, imagine you have a thousand files tagged 'foo' and you're using a
file chooser in a GUI. As soon as you navigate into the 'foo' directory
you're gonna get a thousand files listed, even though you actually wanted
to drill down further, to those tagged with 'foo', 'bar' and 'baz'. These
thousand files are noise you don't want, because you haven't finished
specifying the query you want yet.

The 'files' directory lets you choose when to stop. Now you can browse to
'foo', easily see the other tag directories and browse into 'bar' and then
into 'baz'. Then you can navigate into 'files' (/mp/tags/foo/bar/baz/files)
and get your thirteen files you have tagged with this particular set of
tags, rather than the full thousand.

So that's how it's supposed to work. If it's not working like that, give me
a little more detail and I'll look into it.

Screenshot or copy pasta from your terminal world help illustrate, if there
is an issue.

**Comment by ykhurshid** [comment]
Ah, I understand the reasoning. I'll go ahead and close this issue as the behaviour works fine for me. Thanks for the help!
