### ISSUE TITLE
Mounted Virtual File System tags directory: directory structure should match tag implications

### ISSUE THREAD

**Issue by amitnovick** [oniony/TMSU#170]
#  Start of story, feel free to skip if you want to get to my Question / Suggestion sections

Hello,

To my observation, humans find it intuitive to use semantics in order to group concepts with some shared properties to them.

For instance, it is commonplace for people to use the following semantics for directories on their file systems:
- `Documents`
- `Downloads`
- `Pictures`
- `Videos`

However, historically the file systems chosen for computer systems contained a severe flaw: a single file could only have a single parent directory at any given time.

In practice, this means that a file of type document which you downloaded, could only reside directly under the `Documents` or under the `Downloads` directories.

A savvy user might attempt to work around this limitation with the following technique:
- Put the `Documents` inside the `Downloads` directory
- OR Put the `Downloads` inside the `Documents` directory

This workaround is obviously insufficient to the acute observer:
- What if the user has documents that haven't been downloaded? now the user needs another directory for files that weren't downloaded, say, `notDownloads` and put an additional `Documents` directory inside that one.
- What if the user has downloaded files which are not documents? now the user needs another directory for that type of file and put an additional `Downloads` directory inside that one.

In essence, directories mirror the limitations of the physical world: a single object cannot be placed inside two distinct containers at the same time.

What a shame. one cannot construct a concise semantics tree with this limitation in place.

Enter TMSU
(@oniony walks into the stage, proclaiming:)

> Your file system is flawed? no worries. Just generate a Virtual file system that would sit on top of it, instead.

> In order to apply semantics to a file, apply a list of tags to it via the `tag` command, which will serve as multiple parent directories of that file

> In order to apply semantics to a tag, attach an implication from another tag into it using  the `imply` command.
 
# End of story

Or... maybe not yet the end of that story? I mean when you look around, TMSU and similar VFS efforts haven't really poked a dent into what personal computing looks like in the large.

My view is that TMSU has fundamentally broken through and innovated beyond traditional file system limitations.
However, in order to become a tool that I could wholeheartedly recommend as a solution useful to an everyday computer users, it's still missing a lot of features.

And it's going to be a lot of work to bring those features in, and I know that the resources needed are hard to meet for any unsponsored open source initiative, so I'm not going to pretend that i'm a consumer of a commercial product and "demand" somebody else addresses these concerns on my behalf. to me, the rationale for bringing this up is to first and foremost hold a discussion to see if anybody else is interested in contributing towards the same kind of features as I am. this would help split the resources spent among more developers and make a better tool for all of us in the end.

**I have many features on my radar that I'm interested in**.

# Goal Question
The quoted phrase on the [TMSU homepage](https://tmsu.org/) says:
> TMSU was born out of frustration with the hierarchical nature of filesystems

Does this phrase mean something concrete, as in, that the goal of TMSU's development is to have something that significantly departs from the hierarchical nature of filesystems?

The answer to this question is very important to me, as it would instantly tell me if the vision that I have is shared by @oniony which is currently the main developer.

As I have described above in greater details, I am not opposed to hierarchical organization of files, but merely find one flaw (one parent directory per file) that I'd want to have fixed, and VFS is a solution to that.

I want hierarchical file navigation, but have tags as the hierarchical primitive instead of directories.

# Suggestion
Consider this as the first and main focus for me right now:

**The structure of the `tags` directory inside the mounted directory of the Virtual file system should match the tree of tag implications.**

#### List of tags:
- Pictures
- Trips Abroad
- Photos of Nature
- Photos of Me with Friends
- Trip to Spain Summer 2018
- Trip to Uruguay Fall 2016
- Photos of Barcelona

#### Implications
```
Pictures -> Trips Abroad
Pictures -> Photos of Nature
Pictures -> Photos of Me with Friends
Trips Abroad -> Trip to Spain Summer 2018
Trips Abroad -> Trip to Uruguay Fall 2016
Trip to Spain Summer 2018 -> Photos of Barcelona
```

## Expected behaviour:
```
 ~/tags $ ls
Pictures
```

```
 ~/tags/Pictures $ ls
Trips Abroad
Photos of Nature
Photos of Me with Friends
```

```
 ~/tags/Pictures/Trips Abroad $ ls
Trip to Spain Summer 2018
Trip to Uruguay Fall 2016
```

Any files that are tagged by any of the above tags, should be listed after the implied tags.

For example:
```
 ~ $ tmsu tags "Trip to Spain Summer 2018"
/path/to/Funky Monkey in Gibraltar.png
```

```
 ~/tags/Trip to Spain Summer 2018 $ ls
Photos of Barcelona
Funky Monkey in Gibraltar.png
```

Because the following implication exists:
```
Trip to Spain Summer 2018 -> Photos of Barcelona
```

then `Photos of Barcelona` appears before `Funky Monkey in Gibraltar.png`

## Current behaviour
```
 ~/tags $ ls
files
Photos of Barcelona
Photos of Nature
Photos of Me with Friends
Pictures
Trips Abroad
Trip to Spain Summer 2018
Trip to Uruguay Fall 2016
```

```
 ~/tags/Pictures $ ls
files
Photos of Nature
Photos of Me with Friends
Trips Abroad
```

```
 ~/tags/Pictures/Trips Abroad $ ls
files
Trip to Spain Summer 2018
Trip to Uruguay Fall 2016
```

```
 ~/tags/Trip to Spain Summer 2018 $ ls
files
Photos of Barcelona
```

# Conclusion
Feel free to share your thoughts about this!
I'm primarily curious to hear:
- @oniony 's answer to `Goal Question` section.
- Whether anyone is interested in having the behaviour I described in `Suggestion` section, and prefer it to the current behaviour.

**Comment by oniony** [comment]
Well firstly thanks for getting in touch. From what I can tell you simply
want the tags directory to reflect implications? And to know my motivations.

In terms of my vision, I want tags as a first-rate concept in a filesystem,
instead of directories, but that's not going to happen without writing a
new operating-system and that is a singularly huge undertaking. It would be
possible to add a filesystem that masquerades as a directory-based system
and perhaps that's what TMSU should have been, but there are certain
disadvantages to this approach, not least my inexperience in writing
filesystems.

So TMSU is my pragmatic offering to layer something similar to what I
wanted over (or, more accurately, alongside) the existing directory-based
filesystem. In userspace, without the need to write drivers.

There are loads of features I would write if I had the time and motivation
but I think TMSU is pretty useable in its current state.

With regards to implications as directories. I'm not sure about this. I'll
have a think about it. To be honest I have mixed feelings about the
implications system as a whole as it adds a whole lot of complexity. But I
think it's natural to think of tags implying others.

**Comment by feelextra** [comment]
> Well firstly thanks for getting in touch.
Thank you for the prompt reply and for sharing your thoughts with me!

>  From what I can tell you simply want the tags directory to reflect implications?

Yes, exactly

>  It would be possible to add a filesystem that masquerades as a directory-based system and perhaps that's what TMSU should have been, []...],  TMSU is my pragmatic offering to layer something similar to what I wanted over (or, more accurately, alongside) the existing directory-based filesystem. In userspace, without the need to write drivers. 

I agree that it's much easier of an undertaking, and therefore probably the most pragmatic one.

> There are loads of features I would write if I had the time and motivation 

I'm curious to hear what some of your most wanted features are!

> With regards to implications as directories. I'm not sure about this. I'll have a think about it. To be honest I have mixed feelings about the implications system as a whole [...]. But I think it's natural to think of tags implying others.

I see. well for me implications are integral to the entire use-case of this tool. 

I'm curious to know if implications are a newer concept in the history of development of TMSU, or if it was part of the original vision for it?

Implications to me is just the name for the functionality of tagging other tags.
The way it looks to me, is that `imply` should not work much differently from `tag`. The fact that the target is a tag or a file is merely an implementation detail.

> The implications system as a whole [...] adds a whole lot of complexity.

I'm interested to learn more about the codebase.
Especially I would like to learn how to use the magic sauce that is the VFS for creating directories according to some logic.
Unfortunately i'm not an experienced Go programmer, so strictly reading the source is going to be very difficult.

I did read references to FUSE. is [this](https://github.com/libfuse/libfuse) the interface that I should understand for doing these things? is there any piece of the TMSU codebase that can help me understand how to use the interface in order to do what the TMSU tool does with the VFS? any help with that would be appreciated!

Thank you so much! :blue_heart:

**Comment by feelextra** [comment]
I'm trying to see how to change the behaviour to allow for the suggestion I proposed.

Is it true that whenever the filesystem gets an event to show a content of a tags directory, it would send an SQL query for all existing tags, and then compute:
1. which tags should be found in the directory through the implications system
2. which files should be found in the files directory, again through the implications system

Please point out if this description is somehow inaccurate.
Also, I omitted how the computation works of the tags and files is carried out only because I haven't found out yet.

Your code is very readable! I was able to follow it with zero Go literacy and picked up the basics pretty much.

From what I've gathered so far:
1. In cli/fusevfs.go : on (vfs FuseVfs) method OpenDir:
call `vfs.store.Begin()`
call `vfs.tagDirectories()`
2. In vfs/fusevfs.go: on (vfs FuseVfs) method tagDirectories:
call `vfs.store.Tags(tx)`
3. In database/tag.go: on Tags function:
define:
```
sql := `
SELECT id, name
FROM tag
ORDER BY name`
```
call `tx.Query(sql)` to obtain rows
call `readTags(rows)` to obtain tags
return tags

**Comment by amitnovick** [comment]
I thought about this for a while, and at this point I think that a VFS is not necessary.

The reason why I thought VFS would be useful is because it makes existing tools for filesystem management available out of the box (e.g. search, navigation).

However, the essential data structure for the filesystem needed to realize my suggestion is a true Directed Acylic Graph.

**Any tool built for existing tree-based filesystems is insufficient** at providing:
- Search that eliminates duplications (try using `find .` on the root of a TMSU VFS where a file has two tags and you'll see it appearing twice in the results).
- Multiple parent tag navigation (there is no "going up" / "going down", a choice must be made which parent is to be navigated into).

In my view, the DAG should be a dedicated data structure with specific app-specific operations that make sense.

The only software that gets close to a DAG-based filesystem is TheBrain, although to my taste it seems to put too much emphasis on visualizing the navigation through the graph (with rich animations) but perhaps not enough at search filtering based on tags.

Lately I've been prototyping an Electron-based desktop app that makes use of an actual graph database for storing the relationships, and wish to coerce a DAG restriction on it for the filesystem operations. Don't have a lot of time to work on it, but I'm making progress every once in a while. Isn't really usable in current form unfortunately.

Thanks for giving me inspiration to move forward through this great project of yours!
Regards
