### ISSUE TITLE
Moving a file into a tag directory should tag it

### ISSUE THREAD

**Issue by pixelzerg** [oniony/TMSU#192]
This is quite related to #69 however, I was wondering if it would be possible to provide the option that _moving_ files into a tag directory would tag it.

This might be implemented in this way: if a file is moved into the tag directory, the program should move the file into a user-defined location and apply the required tags to it.

Example directory:
```
/tmsufolder/files/ # just a dump of files
/tmsufolder/mnt/ # tmsu mount point
```

What I want:
```
> mv /some/location/cat_image.jpg /tmsufolder/mnt/tags/animal/=cat/
> ls /tmsufolder/files/
cat_image.jpg
> tmsu files animal=cat
/tmsufolder/files/cat_image.jpg
```

**Comment by oniony** [comment]
I looked into this when I did the virtual filesystem. It wasn't possible
because the FUSE event does not have the original file location. Instead, a
move (across filesystems) causes the file contents to be sent as a stream
of data to the destination (FUSE) filesystem. Unless this has changed since
(I've not looked), you're going to have to use soft links via the ln
command.

**Comment by pixelzerg** [comment]
> a move (across filesystems) causes the file contents to be sent as a stream
of data to the destination (FUSE) filesystem

I am not familiar with FUSE but can't this stream be redirected to another location? In this case, the user-defined location.

**Comment by oniony** [comment]
It can, but that is not what TMSU is about. Perhaps you should look at
Tagsistant.

**Comment by pixelzerg** [comment]
Thanks

**Comment by solarkraft** [comment]
That's incredibly sad. Ironically it wouldn't be an issue if the virtual file system wasn't FUSE mounted, but real symlinks in a monitored directory on the same file system.
