### ISSUE TITLE
This tool is dead, isn’t it?

### ISSUE THREAD

**Issue by tpihl** [oniony/TMSU#198]

**Comment by oniony** [comment]
Spam

**Comment by tpihl** [comment]
Was not intended as spam, it's important to know if something is maintained or dead. And last commit is from 2019. What is the status of TMSU?

**Comment by oniony** [comment]
The status is I'm not finding time to work on it at the moment. It's not
dead as you can happily use it in its current incantation. I will update it
when I have time and inclination.

**Comment by oniony** [comment]
Oh, and it is spam because this is a ticket in the bug tracking system.
General chat should go on the mailing list.

**Comment by timor-raiman** [comment]
By the way, last message in the mailing list is from September 2018..
Having this discussion as an issue is useful, as I was wandering the same thing and the reply here was helpful.

Thanks!

**Comment by oniony** [comment]
Simply no. The TMSU issue tracker is for bugs and feature suggestions only.
It's not a place for any other kind of discussion. Especially not
judgemental/derisory comments like "this tool is dead", which it clearly
isn't because it clearly still can be compiled, installed and used.

Also the last date of the last message in the mailing list has no bearing
on what the issue tracker should be used for.
