### ISSUE TITLE
Untagging a file does not totally remove it from the VFS views

### ISSUE THREAD

**Issue by mpeter50** [oniony/TMSU#236]
For example, I have a file named `mysong.mp3` in a directory managed by TMSU.
It has the tags `music` and `good`, so if the VFS is mounted to the `tagfs` directory, the file is accessible on this path:
```
tagfs/tags/music/good/files/mysong.mp3
```
And also on this one:
```
tagfs/tags/music/good/mysong.mp3
```

If I untag the file, either by `tmsu untag mysong.mp3 good` or `rm tagfs/tags/music/good/mysong.mp3`, the tag will be deleted, as `tmsu tags mysong.mp3` will show that it only has the `music` tag, but the file is still accessible on the 2 paths mentioned earlier.
The file however is not shown, if listing the contents of `tagfs/tags/music/good/files`.

The TMSU version on which I've experienced this is 0.7.5

**Comment by oniony** [comment]
Hi,

Yes, any file is accessible via any valid tag path, whether it's tagged with those tags or not: I never bother to check whether the tag paths are actually valid. It could (at a performance cost) if that's a useful feature or the current behaviour is harmful.

What you have omitted in your description is that the files within the VFS actually contain a file identifier within their filenames, so instead of `tagfs/tags/music/good/files/mysong.mp3`, the path would be something like `tagfs/tags/music/good/mysong.123.mp3`. The VFS simply plucks the `123` from the file name, resolves that to a file and gives you access.

Thanks,
Paul

**Comment by mpeter50** [comment]
> Yes, any file is accessible via any valid tag path, whether it's tagged with those tags or not ...

Oh, ok that changes things. It is not harmful, but I thought that it might be because of an update not triggering.
Also, when I wrote the issue I didn't check if the file is there in the `../files` directory, I actually only checked this when I changed the title :D

> What you have omitted in your description is that the files within the VFS actually contain a file identifier within their filenames ...

forgot about that, sorry. In my other issue I copied paths and log excerpts, and then edited the file names to examples (so the file id is missing in those paths too), and forgot about the id part.
