### ISSUE TITLE
Failed to open tag directory

### ISSUE THREAD

**Issue by akhayyat** [oniony/TMSU#29]
This is my first time trying out TMSU.

I created a local database (`tmsu init`), tagged a file with a couple of tags, mounted the VFS, and browsed it in the terminal. All went well thus far.

Then, I browsed the VFS in my graphical file browser (Thunar). Once I browsed a tag directory to see files tagged with that tag in Thunar, Thunar showed an error message:

    Failed to open directory "<my-tag-name>".
    Software caused connection abort.

So, I went back to the terminal, and now browsing any directory under the VFS in the terminal gives the error:

    ls: cannot access <any-path-under-VFS>: Transport endpoint is not connected

While looking for similar reports on the web, I saw the suggestion to mount the VFS in the foreground using a command such as `tmsu vfs .tmsu/db tagfs` (`tagfs` is my mountpoint). However, this command never succeeds, even before any problems take place. Issuing this command results in:

    /bin/fusermount: mountpoint is not empty
    /bin/fusermount: if you are sure this is safe, use the 'nonempty' mount option
    tmsu: could not mount virtual filesystem at '.tmsu/db': could not mount virtual filesystem at '.tmsu/db': fusermount exited with code 256

I assure you, the `tagfs` mountpoint is absolutely empty! Or at least as far as `ls -a` can tell.

Please help! This has not been a pleasant experience so far :(.

**Comment by oniony** [comment]
Hello Ahmad,

Sorry to hear you are having problems with TMSU. There is a known issue with the VFS in version 0.5.0 and 0.5.1. I have fixed it on the default branch but have yet to push out 0.5.2. I hope to do so on the train this evening.

In the mean time, if you are able to compile from source then you should find this issue fixed. If not, please let me know.

Regarding mounting using the `vfs` command, the syntax changed in 0.5.0: the database is no longer specified as the first argument. It now works the same way as the other commands:

    tmsu -v vfs path/to/mountpoint

The -v produces verbose logging which is useful if there is an error. You could try this and see if you are getting the 'transaction already open' error that I fixed in the past few days or if you are getting a different error I need to look at.

Thanks,
Paul

(I'll leave this open until you have confirmed it's the same issue.)

**Comment by akhayyat** [comment]
Thanks for the quick and to-the-point response!

I confirm that I can see this *panic* now with the proper `vfs` command:

    panic: could not begin transaction: there is already an open transaction

**Comment by oniony** [comment]
OK, this smells very much like the existing issue #28. If you can bear with me a day then I will push out a 0.5.2 with a fix for this otherwise you are more than welcome to compile from the sources and try that.

Sorry your first experience with TMSU has not been a positive one!

**Comment by oniony** [comment]
Please give the new [v0.5.2 release](https://github.com/oniony/TMSU/releases/tag/v0.5.2) a try. I would be very interested to know if this fixes this issue for you.

**Comment by akhayyat** [comment]
Works perfectly.. Thank you!

**Comment by gcavallo** [comment]
I'm having a similar issue with 0.6.0 when opening an empty tag folder. If I create a tag without tagging any files to it, opening it's folder with ls or thunar/nautilus will fail:

    ~$ tmsu mount ~/TMSU
    ~$ mkdir TMSU/tags/Empty
    ~$ ls TMSU/tags/Empty/
    ls: cannot open directory 'TMSU/tags/Empty/': Software caused connection abort
    ~$ ls TMSU/tags
    ls: cannot access 'TMSU/tags': Transport endpoint is not connected

The only way I've found to fix this is by unmounting with `fusermount -uz` and delete the tag with tmsu (deleting the mounted folder with rm will fail).

So far only empty directories are causing this issue, browsing tags with files does work fine.

**Comment by oniony** [comment]
Hi, thanks for raising this and sorry to hear you're having problems. However this issue is closed so this would be better in a new ticket, I think. That way I can assign it to a release and classify it, &c.

If you could raise a new one with the same text then that'd be better as you'll get notifications when it's fixed. If you've don't, I'll copy the text to a new issue later today.

Thanks,
Paul
