### ISSUE TITLE
Fulltext tag values

### ISSUE THREAD

**Issue by tomassedovic** [oniony/TMSU#37]
Would it be possible to add full text tags? For things like summary of a TV episode, song's lyrics, etc.

The full text values would be different from the existing values in that they're arbitrary long, without character restrictions and usually unique for each file & tag.

It would probably require a new command line option:

    $ tmsu tag summer.mp3 music big-jazz mp3 --text "comments=Best. Song. Ever."

which would save the value `Best. Song. Ever.` for file `summer.mp3` and tag `comments`.

**Comment by oniony** [comment]
This is something I have considered. Indeed it's on the [TODO list](https://github.com/oniony/TMSU/wiki/TODO) list (under 'low').

It would certainly be possible to do, for values at least. I don't think it would require any special option: the quotes alone should make the intent clear.

**Comment by tomassedovic** [comment]
Oh, cool!

Not sure the quotes will be enough, though. I just tried argv in Python and C (don't have Go installed now but I imagine it'll work the same). Passing `comments="Best. Song. Ever."` means the program receives the string `comments=Best. Song. Ever.` (no quotes). But there are other ways (e.g. if the value is invalid, treat it as full text).

I may send you a pull request at some point if you're open to it. In case you are, do you want to just extend values to accept whitespace and punctuation or have the fulltext ones treated separately?

**Comment by oniony** [comment]
Yeah, it'll take some care but it should be fairly straightforward.

I'm happy for pull requests but please don't be offended if I don't apply them verbatim. I see this as simply handling whitespace rather than new 'fulltext' funcitonality so I wouldn't expect there to be any new option: simply that the following will then be possible:

    $ tmsu tag somefile tag="value with spaces"
    $ tmsu tag somefile tag='value with spaces
    $ tmsu tag somefile tag=value\ with\ spaces

When I've thought about this in the past it seemed relatively straightforward as the shell should do the parsing for you and put the whole string, spaces and all, into a single ARGV array element.

The complications come from other aspects:

* 'tmsu files' supports queries and so TMSU currently joins the ARGV arguments together with spaces between before parsing the query language. This could potentially be handled by enquoting each element before joining with spaces and then upgrading the query parser to handle quotes.
* 'tmsu tag -' allows the user to tag from standard input or other file in which case there is no shell parsing support.
* The virtual filesystem exposes the tags/values as directories. I imagine this will work fine without changes but there could be unforeseen problems.

**Comment by oniony** [comment]
It would also have to support spaces in the --tags option:

    tmsu tag --tags="tag='value with spaces' othertag"
    tmsu tag --tags='tag="value with spaces" othertag'
    tmsu tag --tags="tag=value\ with\ spaces othertag"

**Comment by oniony** [comment]
There is a tokenizer in tmsu/common/text for tokenising a string into fields with consideration for quotes.

**Comment by oniony** [comment]
This is being implemented as part of issue #45.
