### ISSUE TITLE
Tag values are difficult to work with

### ISSUE THREAD

**Issue by StereoSix** [oniony/TMSU#39]
Creating a tag value without tagging a file doesn't work (i.e., `tmsu tag --create author=bob`) because it's interpreted as a tag with a comparison operator ('='). This is particularly janky since `tmsu help tag` includes it as a use case.

Tag values also can't be renamed, merged, part of implications, etc. since the commands interpret `author=bob` as a whole tag. I see some of this in your TODO, though.

**Comment by oniony** [comment]
Thanks for pointing these issues out. I'll take a look.

**Comment by oniony** [comment]
>Creating a tag value without tagging a file doesn't work (i.e., `tmsu tag --create author=bob`) because it's interpreted as a tag with a comparison operator (`=`). This is particularly janky since tmsu help tag includes it as a use case.

This issue is 'fixed' in 64e28cc. I use the quotes as it is a bit strange in use:

    tmsu tag --create some

This creates the tags `some` if it did not already exist. If a specified tag already exists the command will report this to the error stream and return with a non-zero return code. This bit is fine.

    $ tmsu tag --create some=thing

This now creates the tag `some` if it did not already exist and creates the value `thing` if it did not already exist. This form will report an error and return with a non-zero return code only if the *value* already exists. This *seems* fine initially...

Although we're creating a tag+value tuple, the value is in no way associated with the tag specified. TMSU (currently) has tag to value 'schema', so you can really use any tag prior to the equals with identical results. Indeed, if you run the `values` command to list the values for the tag we *just used to create it* you will see there are no results:

    $ tmsu tag --create some=thing
    $ tmsu values some
    $

So perhaps the `tag` command should not be used to create values in the first place. Perhaps there should be a `value` command for managing values, with its own `--create` option. Otherwise, maybe it should be enough to prefix the name with an equals to make the intent clear without having to use a dummy tag:

    $ tmsu tag --create =cheese

Though it is still strange we're saying "TMSU, on the subject of tags, please create me one, but actually I really want a value instead, and I'd like it to be called 'cheese'."

**Comment by oniony** [comment]
>Tag values also can't be renamed, merged, part of implications, etc. since the commands interpret author=bob as a whole tag. I see some of this in your TODO, though.

Yes this is something I'm concious of. One thing I have been thinking about recently is that the separate commands for applying tags (`tag`), renaming tags (`rename`), merging tags (`merge`) and deleting tags (`delete`) were great when tags were the only entities TMSU could work with. Now that there are values, implications and settings, the interface is rather inconsistent when it comes to managing them:

* create
  * tag: tmsu tag --create tagname
  * value: tmsu tag --create x=valuename
  * implication: tmsu imply tagname1 tagname2
  * config: n/a
* apply
  * tag: tmsu tag file tagname
  * value: tmsu tag file tagname=valuename
  * implication: n/a
  * (amend) config: tmsu config name=value
* list all
  * tags: tmsu tags
  * values: tmsu values
  * implications: tmsu imply
  * config: tmsu config
* list
  * tags for a file: tmsu tags filename
  * values for a tag: tmsu values tagname
  * implications for a tag: *not possible*
* delete
  * tag: tmsu delete tagname
  * value: *automatic when no longer applied*
  * implication: tmsu imply -d tag1 tag2
  * config: n/a
* rename
  * tag: tmsu rename tagname newname
  * value: *not possible*
  * implication: n/a
  * config: n/a
* merge
  * tags: tmsu merge tag1 tag2
  * values: *not possible*
  * implications: n/a
  * config: n/a
* copy
  * tags: tmsu copy tagname newname
  * values: *not possible*
  * implications: n/a
  * configs: n/a

So I have been wondering if it would be better to make these all as consistent with each other as possible. One idea would be to change the commands to be nouns rather than verbs:

* create
  * tag: tmsu tag --create tagname
  * value: tmsu tag --create x=valuename
  * imply --create tagname1 tagname2
  * config: n/a
* apply
  * tag: tmsu tag file tagname
  * value: tmsu tag file tagname=valuename
  * implication: *automatic*
  * (amend) config: tmsu config name=value
* list all
  * tags: tmsu tags
  * values: tmsu values
  * implications: tmsu implies
  * config: tmsu configs
* list
  * tags for a file: tmsu tags filename
  * values for a tag: tmsu values tagname
  * implications for a tag: tmsu implies tag
* delete
  * tag: tmsu tag --delete tagname
  * value: tmsu value --delete valuename
  * implication: tmsu imply --delete tag1 tag2
  * config: n/a
* rename
  * tag: tmsu tag --rename tagname newname
  * value: tmsu value --rename valuename newname
  * implication: n/a
  * config: n/a
* merge
  * tags: tmsu tag --merge tag1 tag2
  * values: tmsu value --merge value1 value2
  * implication: n/a
  * config: n/a
* copy
  * tag: tmsu tag --copy tagname newname
  * value: tmsu value --copy valuename newname
  * implication: n/a
  * config: n/a

The other possibility is to keep (and extend) the existing verb commands but add options to switch the entity they operate upon. This may be better as most operations revolve around tags and this could be the default behaviour when entity option is omitted:

* create
  * tag: tmsu create [--tag] tagname
  * value: tmsu create --value valuename
  * implication: tmsu create --imply tagname1 tagname2
  * config: n/a
* apply
  * tag: tmsu tag file tagname
  * value: tmsu tag file tagname=valuename
  * implication: n/a
  * (amend) config: tmsu config name=value
* list all
 * tags: tmsu list [--tag]
  * values: tmsu list --value
  * implications: tmsu list --imply
  * config: tmsu list --configs
* list
  * tags for a file: tmsu list [--tag] filename
  * values for a tag: tmsu list --value tagname
  * implications for a tag: tmsu list --imply tag
* delete
  * tag: tmsu delete [--tag] tagname
  * value: tmsu delete --value valuename
  * implication: tmsu delete --imply tag1 tag2
  * config: n/a
* rename
  * tag: tmsu rename [--tag] tagname newname
  * value: tmsu rename --value valuename newname
  * implication: n/a
  * config: n/a
* merge
  * tags: tmsu merge [--tag] tag1 tag2
  * values: tmsu merge --value value1 value2
  * implication: n/a
  *config: n/a
* copy
  * tag: tmsu copy [--tag] tagname newname
  * value: tmsu copy --value valuename newname
  * implication: n/a
  * config: n/a

**Comment by oniony** [comment]
I've just realised I overlooked automatic value deletion in my earlier commit.

Unlike tags, which can be created and deleted manually, values are currently automatically deleted when they are no longer used. The rationale for this is that the user will be actively managing the set of tags (the tag 'schema') whereas the set of values is likely to be larger and more difficult to manage. For example, the user might create 'country' and 'year' tags each with tens of values.

So to have the 'tag --create a=b' create the value breaks this in creating an unused value which is then impossible to delete except by applying it to a file and then removing it again.

For now I am going to back out my earlier change. A decision will need to be made on whether to keep with the existing automatic value management or put the onus onto the user to actively manage them.

**Comment by oniony** [comment]
Action plan:

1. Facility for renaming values.
2. Facility for explicitly deleting values.
3. Facility for merging values.
4. Allow values to participate in implications.
5. Reconsider whether automatic value deletion is desirable.
  a. If not, a facility for manual value creation should be added.

**Comment by oniony** [comment]
Facility fo rename values in cd12387.

**Comment by oniony** [comment]
These changes should address most of your requirements. In implementing this I realised it might be nice to have more sophisticated implications of the likes of:

    year >= 1837 and year <= 1901 implies victorian

But that'll have to wait for another day.

Let me know if you have any problems.
