### ISSUE TITLE
Relax restrictions on permitted characters in tag/value names

### ISSUE THREAD

**Issue by oniony** [oniony/TMSU#45]
Currently there are a number of restrictions on which characters are allowed to be used in tag and value names. These are present for several reasons:

1. To make parsing file queries easier.
2. To avoid invalid names when mounting the virtual filesystem.

Category 2 consists only of the slash characters, the backslash being illegal on Windows and the forwardslash on most other platforms.

Items that fall into category 1 should be relaxed where possible.

* Changes to the scanner should make it possible to use backslash escaping for problematic characters thus allowing their use within tag and value names.
* More difficult to remove would be restrictions on keywords that are used as operators in the query language, e.g. 'and', 'or', 'not', 'lt', &c..

TODOs
---

* ~~subcommand `files` to render `=` delimiter in colour (when colour turned on)~~
* ~~facility for customizing the TMSU colours (*à la* `LS_COLORS`).~~
* ~~fix bug with `tag --tags` not handling whitespace (and presumably literal `=`).~~
* ~~test coverage for all problematic characters.~~
* ~~Zsh completion to correctly escape characters that are used by the shell.~~
* ~~update wiki on names and explain how to handle both shell and TMSU escapes for problematic characters.~~

**Comment by oniony** [comment]
Removed restrictions on punctuation except for slashes which cannot be used in filenames on Windows and/or Posix.

When running a query using the 'files' subcommand, problematic characters can now be escaped with a backslash:

For example:

    tmsu files 'year < 2015'
    tmsu files 'year\<2015'

The first example identifies files with a year tag less that 2015 whereas the second retrieves files tagged with 'year<2015'.

**Comment by oniony** [comment]
TODO update wiki.

**Comment by 0ion9** [comment]
Just checked out the commit, and tried to test it:

```
mkdir /tmp/t
cd /tmp/t
tmsu init
echo > foo
tmsu tag foo 'escaping\=test'
```
Result: `tmsu: could not create tag 'escaping\': tag names cannot contain backslash: '\'` (I tried a few other variants with different quoting or numbers of \, none worked)

Conclusion: `tmsu (un)?tag` doesn't understand escapes yet.

* I later verified that `tmsu files` behaved correctly after using sqlite3 directly to rename a tag so it contained a `=`.
* Then I checked that 'tmsu rename' allowed un-escaped equals (`tmsu rename esc=ape ape=esque`), which worked
* and that I could implicate to tags which contained '=', which didn't (escaped or unescaped, the result was implication to the tag=value pair ape = esque). Implicating a tag which contained < worked, IFF the < wasn't escaped. ).
* I also checked that the output of `tmsu tags` was properly escaped (ie. the tag 'foo=bar' should be  written 'foo\=bar', whereas the tag-value pair 'foo'='bar' should be written 'foo=bar'), which it wasn't.
* Finally, I did a similar check that implications to values containing = were properly escaped (eg. the pair 'eq' = '==' should be returned as 'eq=\=\='), which it wasn't.

HTH, FWIW.

**Comment by oniony** [comment]
Hi,

Yes there are a few problems right now. Consider it a work in progress. (My
train journey inconveniently ended :) I'll close the issue when I consider
it 'done' but I imagine there'll be a fair few bugs from this change. I'll
try to add more tests around the names too.

Backslashes are not allowed in names, BTW, as it would make it impossible
to do a Windows VFS. But you're right that it should be possible to escape
the equals, I'll fix it up. In fact, do you want to update the issue with
your findings as you notice stuff and I'll work through it? (If you want
to, of course.)

Thanks,
Paul

**Comment by 0ion9** [comment]
> Backslashes are not allowed in names, BTW, as it would make it impossible to do a Windows VFS.

Yes, I didn't have a problem with that, but of course tagging the file 'escaping=test' would be expected to produce a tag=value pair rather than a tagname containing =, so my expectation was that I needed to escape it. Overall I concluded escaping needs to be supported on both (TAG and VALUE) sides when tagging, on both sides when reporting the tags of files, and similarly for both sides of data reported by 'tmsu imply'.

I'll be happy to do updates (most likely after you do commits and I try to break them, but possibly at other times too ;)

**Comment by oniony** [comment]
TODO Zsh completion needs to be updated to escape equals in tag names where appropriate.

**Comment by oniony** [comment]
TODO add some tests.

**Comment by 0ion9** [comment]
Okay, I've had some time to catch up and this is the latest breakage I found:

```
cd /tmp
echo > foo
tmsu tag foo esc\=aped equ=al '>:|' '.=.' 
```


Output is '.=.  >:|  equ al  esc aped'.
Now, to be clear, there is a = symbol there between equ and al, and between esc and aped. It just shows up as a blank in my terminal (Sakura, with a fair suite of unicode fonts including GNU Unifont.)

This is quite interesting since for example, if I run `tmsu tags foo | cat`, the equals signs in the output are perfectly visible.
But in the plain `tmsu tags foo` output does not show the equals signs at all.

I understand why you'd do a slightly different output for TTY and non-TTY destinations. I'm currently having a little trouble tracking down what that intermediate character is, though
(since pasting it seems to translate it to a normal =)

Another bug: tmsu files $FOO, where $FOO is a set of tags including escaped =, does not work:

```
TAGS=($(tmsu tags foo| cut -d : -f 2-))
echo ${#TAGS[@]} 
```
4 

(correct)

```
printf "%s,%s,%s,%s" "${TAGS[@]}"
```
.\=.,>:|,equ=al,esc=aped

(correct; so I've verified the array content is exactly what we expected)

```
tmsu files "${DATA[@]}"
```
(no result)

(incorrect.)

Further, if we assume I got the quoted array expansion wrong somehow, and just stick in the literal values into a commandline, appropriately quoted:

```
tmsu files '.\=.' '>:|' 'equ=al' 'esc=aped'
```

The output is still nothing, though it should be `foo`.

I spotted the bug here after a little bit -- it is that the > is not escaped when 'tmsu tags' outputs it. Changing '>:|' to '\>:|' causes the query to correctly return `foo`.

**Comment by oniony** [comment]
Thanks for this. I'll have a look through this more properly on my commute tomorrow.

As for the equals sign, I'm actually printing a regular equals but coloured bold black which appears as grey on my terminal. I'll try it on a couple of other terminals. Seems I'll have to pick another colour, which I didn't want to do as it's a bit distracting having the equals sign coloured. Perhaps I'll just show the equals in tag names escaped regardless of whether colour is on or not.

**Comment by oniony** [comment]
OK, I think the first case (where the equals is missing) is purely a rendering issue on your terminal. In both xterm and urxvt it renders correctly for me. Could you confirm which terminal you are using? Is there any possibility you are using a grey background? Regardless, I'm going to change the code to not bother with colour here: I'll simply always escape the necessary characters regardless of whether the terminal is detected.

As for '.=.', this should not actually be possible as I have reinstated the validation to prevent '.' and '..' as a tag name.

As for the remaining issue, I'll make some changes to ensure output is escaped where appropriate. I'll add some tests while I'm at it too.

Thanks for doing this, it's always very handy to have someone tests these sorts of changes!

**Comment by 0ion9** [comment]
On close examination, I realize the equals *is* showing up. It's a palette issue (Solarized palette):

![tmsu-invis](https://cloud.githubusercontent.com/assets/115782/9218027/e4a85330-410d-11e5-9d3f-ed7d3f681974.png)

I added an inset version that is blown up even more so that you can spot the equals.

**Comment by oniony** [comment]
OK, I think that's all of these cases fixed. I'll add some more tests around escaped output later on.

**Comment by 0ion9** [comment]
1. Just spotted another minor issue, while I was updating my TMSU script for [lighthouse](https://github.com/emgram769/lighthouse) : 

The 'tmsu tag' help still talks about various characters not being allowed in tag names, and also does not talk about escaping characters. As demonstrated by the success of `tmsu tag foo 'e\,q\=u\(a\)\<l\>s\/'` (hopefully GitHub won't mangle that), / is the only character still remaining that cannot be used in a tag name by escaping it.

Suggested amendment:

`Tag names may not contain whitespace characters or the slash symbol (/).
The comparison operator symbols (=, < and >), parentheses (( and )), commas (,) may be used if properly escaped (eg '\>:[').`

This could still use improvement, because it relies on the user to know a bit too much about shell quoting (for example `"eq\\=uals"` and `'eq\=uals'` are the same tag name, containing a single correctly-escaped = character.)

2.
Perhaps the help for `tmsu files` should also indicate that `Any literal =, <, >, (, ), or ',' characters in tag names must be correctly escaped, eg ':\)'`

3. The example of `tmsu tag foo 'e\,q\=u\(a\)\<l\>s\/'` demonstrates outstanding problems, either with validation (in the case that not all these characters are supposed to be allowed when escaped), or with `tmsu tags foo` output.

`tmsu tags foo` output is `e,q\=u(a)\<l\>s` . 

Using this with tmsu files:

`tmsu files 'e,q\=u(a)\<l\>s'`

results in the following errors:

```
tmsu: no such tag 'e,q=u'
tmsu: no such tag 'a'
tmsu: no such tag '<l>s'
```
Personally, I was expecting the , to need escaping here -- but perhaps you changed that, since it doesn't say 'no such tag 'e''. But certainly, the () needs escaping, if escaped () are supposed to be valid.

**Comment by oniony** [comment]
Thanks, I'll take a look. (On my hols at the moment so will be next week.)

**Comment by oniony** [comment]
>The 'tmsu tag' help still talks about various characters not being allowed in tag names, and also does not talk about escaping characters.

Only the equals character actually needs to be escaped in the `tag` subcommand (and only then within the tag name as once the value is being parsed the = delimiter has already been found): as the operators can only be used during queries (`files` subcommand) they have no special meaning to the `tags` subcommand. I have updated the help text but I fear it's a bit overly complex so I may revisit it as there is two levels of escaping going on here, which is mightily confusing.

>Perhaps the help for tmsu files should also indicate that Any literal =, <, >, (, ), or ',' characters in tag names must be correctly escaped, eg ':\)'

I've updated the help for this one. I'm starting to wonder whether allowing these characters was a good idea :)

>The example of tmsu tag foo 'e\,q\=u\(a\)\<l\>s\/' demonstrates outstanding problems, either with validation (in the case that not all these characters are supposed to be allowed when escaped), or with tmsu tags foo output.

Problem here is with the `tags` subcommand output: the parentheses need to be escaped. I've fixed this now too.

**Comment by oniony** [comment]
OK, I feel this issue is nearly complete but before I close it I am going to take a look at allowing whitespace characters within tag and value names.

**Comment by oniony** [comment]
Whitespace is now allowed.

I've noticed the Zsh completion doesn't work properly when <, |, ' ', &c. are used within tag/value names. This will need to be addressed.

**Comment by oniony** [comment]
I'm now wondering whether 'tags' and 'values' should be escaping all of these characters by default. The 'ls' command, for example, doesn't escape shell symbols (< redirects, | pipe, &c.) or whitespace unless instructed to do so. In fact the only symbol that needs clarification during listing is '=' as it would otherwise be unclear whether the '=' is part of the tag name, value name or is the delimiter separating the tag and value names.

Perhaps the correct solution is to *not* escape them when printed but to have the Zsh completion correctly apply escaping such that they will not be confused with the operators.

E.g.

> tmsu tag somefile 'a<b'
> tmsu tags
a<b
> tmsu files _tab_
> tmsu files a\\\<b

**Comment by 0ion9** [comment]
A good choice IMO. However I'd like to point out that it doesn't work with --tags / -t option to `tmsu tag`, which only completes the first tag name. Maybe I should file an issue for that?

**Comment by 0ion9** [comment]
Reposting this as a separate comment because I've been told that edits don't generate notifications:

Edit:
Also, how do you escape whitespace?
tmsu tag --tags 'try\ 8' test.jpg tags the file with two tags, try and 8.
tmsu tag --tags 'try\\ 9' test.jpg says `tmsu: could not create tag 'try\': tag names cannot contain '\'

Edit2: okay, that's a bug. Escaping of whitespace is handled by the
tmsu tag test.jpg 'try\ 10' form but not the tmsu tag --tags 'try\ 10' test.jpg form.

**Comment by oniony** [comment]
Thanks for letting me know. I think what I need to really do here is beef
up the test coverage on tag and value names.

**Comment by oniony** [comment]
TODO fix bug with --tags not handling whitespace (and presumably literal '=').
TODO test coverage for all problematic characters.
TODO Zsh completion to correctly escape characters that are used by the shell.

**Comment by 0ion9** [comment]
I think this has come up before, but I just, well:

```
$ cd /tmp/
$ tmsu init
$ touch f
$ tmsu tag --tags 'foo=bar' f
$ tmsu tag --tags 'foo\=bar' f
$ tmsu tags f
foo=bar  foo=bar
```
To me, that is evidence that = needs to be escaped -- otherwise a person or program is forced to guess what TMSU means by = on a case by case basis. (obviously this particular example is contrived, but `year=2012 \=_\=` is not, for example)

**Comment by oniony** [comment]
Yes, the plan is:

1. Use colour to differentiate the tag/value delimiter equals.
2. As colours can cause the sort of readility issue we saw previously, add support for colour customization via environment variable.
3. Add an option to escape problematic characters.
4. Automatically turn on escaping if output is not to a terminal (not sure about this one).

**Comment by oniony** [comment]
New plan is to escape the `=` character in the output of `tags` and leave it at that. Everything else seems overly complicated for such a niche use-case and I can always revisit this later if it does turn out to be a problem.
