### ISSUE TITLE
Report duplicated files when tagging them.

### ISSUE THREAD

**Issue by eflyinghi** [oniony/TMSU#57]
Could tmsu report duplicated files when tagging them?  Could be configurable by adding a new setting.

Tmsu is a greate tool which I looked for many years.  I planned to use tmsu as a  documents/pictures/videos management system.  So when I added my files to tmsu database, I wanted to knon if the files already existed.

**Comment by 0ion9** [comment]
I've timed this and surprisingly, even for my 1million-file database, performance is quite good . In order to check for duplicates, you internally need to run "SELECT id from file where fingerprint=?". timings (`time sqlite3 .tmsu/db 'select id from file where fingerprint="f34e25aba1238a8fe90285284958902458";'`) ranged from 0.005s to 0.087s.

**Comment by oniony** [comment]
Amusing TMSU used to do this but I removed the feature for some reason. I think it was during the period where I was experimenting how to handle directories.

I could easily add this back in, yes. I'll take a loot. Thanks for reporting.

**Comment by oniony** [comment]
Duplicate reporting turned on by default. Disable with the `reportDuplicates` setting.
