### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Nichtraucher** [oniony/TMSU#62]
Hey,

as the title says: TMSU screams to be used with a gui - or at the very least with some nautilus scripts or so...

I would greatly appreciate anything in this direction!

cheers

**Comment by oniony** [comment]
Hi there. Thanks for the suggestion.

It's occurred to me many times that a GUI of some sort would be useful: indeed TMSU started life as a web project (written in Scala). A GUI would suit photos very well but I've always wanted TMSU to be file agnostic so if TMSU were to offer a GUI then it'd have to be a fully-fledged file browser/manager/commander, which is quite an undertaking, and certainly not one I have time to pursue.

I think it would probably make most sense if another project could integrate TMSU or call into it. Scripts would be perfect as I could easily include scripts for various file managers in the `misc` directory of the distributable.

**Comment by 0ion9** [comment]
sxiv and spacefm both can be made tmsu-aware (eg. so that pasting files transfers tags too, tag-aware renaming, etc..; sxiv status can display tags, etc). It's possible to setup a general tagging GUI via lighthouse.

I say that because they are things I have developed (the former just with shell script; the latter with Python and tmsoup). Currently a few things are hard-coded, I'd like to fix those before releasing it.
All I can really say is that it works pretty completely and easily for me. Having specific support in the application for tagging is a bonus; but I guess the importance of tagging inside the app  depends on workflow.

**Comment by Nichtraucher** [comment]
> I think it would probably make most sense if another project could integrate TMSU or call into it

I have a large bunch of (work-related) scientific documents in different formats (pdf, djvu, epub) that I'd like to use together with a desktop search enging (Recoll - the only one that supports .djvu-files). All other tagging applications have certain disadvantages (lack of file type support etc.) that TMSU doesn't have.

The command-line is a barrier though. I'd gladly give TMSU a try If there would be something that lets me make easy changes (such as adding, removing, copying tags in selected files/folders).

**Comment by 0ion9** [comment]
Looks like I already began on a repo for this: 
https://github.com/0ion9/tmsu4spacefm

Just wrote a 'paste tags' plugin for spacefm and dropped in the script there. My other scripts, as implied earlier, need some surgery before release.

**Comment by oniony** [comment]
OK, I think I'm going to close this as "won't fix". I think a fully-fledged GUI is outside the remit of this project: if I were to build one then I imagine it'd be as a separate project that calls into TMSU or embeds the TMSU as a library. Otherwise I'm happy to accept (simple) scripts for integrating with file managers and bundling these in the `misc` directory of releases.

**Comment by 0ion9** [comment]
@Nichtraucher :
@oniony : Just adding a short note : 
I've thought about this some more and think the central thing (aside from a un/tagging GUI) that would make this work is if you could filter the view by TMSU tags, in the file browser. My ideal model for that would be GIMP / Krita resource tagging with its immediate realtime feedback, but a popup prompt would be a start.

Currently I don't know of any file managers that support custom view filtering. If there is one, I'm happy to look at writing a filtering plugin for it.

**Comment by talklittle** [comment]
For anyone happening across this issue, I have a work-in-progress Nautilus extension for TMSU: https://github.com/talklittle/tmsu-nautilus-rs

Currently (v0.2.0) supports adding tags by right-clicking one or more files; and a Tags column can be toggled in Nautilus list view mode, to show the tags.

I linked to it in the [FAQ](https://github.com/oniony/TMSU/wiki/FAQ#does-tmsu-have-a-gui).

Unfortunately probably too big to include that Rust source code or .so shared library in TMSU repo's `misc` directory. Incidentally I did write a [Python version](https://github.com/talklittle/tmsu-nautilus-python) which is a single script file, but it's slower. Nautilus extensions Python bindings are kind of outdated and buggy, so I don't recommend the Python version.
