### ISSUE TITLE
Parsing ambiguity with filenames containing ': '

### ISSUE THREAD

**Issue by 0ion9** [oniony/TMSU#64]
Yep.. I was aware of this ambiguity but didn't think it would have any real effects. Turns out `: ` is not that uncommon in music file names though.

I don't actually think there's a particularly good solution here -- doing `filename\ttags` is probably the best I can think of, and that just rarifies the ambiguity further, since `\t` is a valid character in eg. [ext4](https://en.wikipedia.org/wiki/Ext4), [btrfs](https://en.wikipedia.org/wiki/Btrfs) (as is `\n`, ugh.)

To illustrate the ambiguity, here is the important part of my parsing code(Python):

    for line in output:
        if ': ' in line:
            parts = line.split(': ')
            start = 1
            lhs, rhs = parts[0], ": ".join(parts[1:])
            # hack to cope with parsing ambiguity
            while lhs not in conversiontable:
                start += 1
                lhs = ": ".join(parts[:start])
                rhs = ": ".join(parts[start:])
                if start > len(parts) or not rhs:
                    # no matching file?
                    # we can't guess correctly
                    # just assume the first ': ' is separator
                    lhs, rhs = parts[0], ": ".join(parts[1:])
                    break
            #.. or maybe entire line?
            if lhs not in conversiontable and line[:-1] in conversiontable:
                lhs = line[:-1]
                tags[conversiontable[lhs]] = empty
                continue
            rhs = rhs.rstrip().split(' ')
            tags[conversiontable[lhs]] = set(rhs)
            tags[conversiontable[lhs]].update(v.split('=')[0] for v in rhs if '=' in v)
        elif line.endswith(':'):
            lhs = line[:-1]
            tags[conversiontable[lhs]] = empty

EDIT: and a short explanation of the above and its bugs:

`conversiontable` is a original_path:real_path map. If a fragment of text has an exact matching key in `conversiontable`, it's probably a genuine filename. 

The loop walks through the possible ways of splitting the line, eg.
in a line `foo: bar: baz', there are two possibilities: 'foo' is the filename and 'bar: baz' are the tags, or 'foo: bar' is the filename and 'baz' is the tags.

More generally, N instances of ': ' -> N possible ways of splitting the input.
This problem is most apparent with files with no extension (eg. given two existing filenames `foo: bar` and `foo`, there is no efficient way to determine conclusively which one TMSU is referring to), and with tags that end with ': ' or contain ': '.

**Comment by oniony** [comment]
So it's the output of `tmsu files` you think needs to be improved? I'm struggling to see how your explanation relates to a specific issue in TMSU.

**Comment by 0ion9** [comment]
Yes. '%s: %s' is ambiguous if either of the strings being formatted contain ': ' - and ': ' is not a terribly unlikely sequence in a filename.
It is for that reason I proposed '\t' (tab) : extremely uncommon in filenames, and if it is present in filenames or tags, how to escape it is already well established (`\t`). Using tab as separator + escaping tab in filenames + tags, would remove the ambiguity (and therefore allow parsing code to be much simpler)

Personally, I tend to normalize filenames so they contain no spaces, but this is not always possible or practical.

**Comment by oniony** [comment]
Solutions:

1. Use an ASCII control character, such as `RS` (record separator) to delimit the fields.
2. Use the `NUL` control character (`^@`).
3. Use the slash character `/`.
4. Use the tab character (`^I`).
4. Allow the user to choose a character.
5. Escape any colons within the filename and escape any spaces within the tag/value names with a backslash (`\`).

The benefit of `RS` is that different control characters could be used to delimit the different parts of the output, e.g. tags and their values can be delimited without the use of `=`. The downside is that these control characters are legal, though unlikely, in filenames on Unix.

The obvious benefit with `NUL` is that it's illegal within filenames. It's also commonly used for this purpose: `find`, `xargs` and `du` are a few tools that allow `NUL` to be output instead of newlines. The downside is that TMSU also uses this to delimit lines when instructed to do so, so it cannot be used for field separation unless we used, say, a double `NUL` to mark the ends of lines.

The slash character also, handily, is not allowed in filenames. It's also readable. However, as of quite recently, TMSU now supports slashes within tags and values and so this character could not be used to delimit tags unless the slashes within the tags are escaped.

Allowing the user to choose a value is a bit of a cop-out. It puts the onus on the user to solve this problem, whereas it would be better if TMSU solved it.

Escaping the problematic characters would solve the problem but make it much harder for people writing scripts to parse the output as they would have to have logic to understand the escaping. However, the output of TMSU `tags` already uses escaping so it would be inconsistent to do anything else. Even with some of the other options, `NUL`, `/` and `^I`, would require escaping where tag names or values contain = symbols (as they already do).

**Comment by oniony** [comment]
My proposition, is option 6, escaping the colons in the filenames with a backslash. It will then be possible to split the output on `:`, so long as it is not preceded by an odd number of backslashes. To explain this, consider the following outputs:

    example1: tag
    example2\:: tag
    example3\\: tag
    example4\\\:: tag

In example 1, there the colon is clearly the delimiter, as it is not escaped.
In example 2, the first colon is a part of the filename because it is escaped (it is preceded by an odd number of backslashes: 1).
Example 3, the colon is preceded by an even number of backslashes (2) so there is a literal backslash in the filename.
In example 4, the first colon is part of the filename because it is escaped (its is preceded by an odd number of backslashes: 3). This means there is a literal backslash and a literal colon in the filename.

So how would one chop this output up? I guess one solution would be to translate the '\\' into something else, e.g. 'BACKSLASH', first. Then translate '\:' into 'COLON'. Finally you can now split on the remaining colon. Finally you'd need to reverse the translations on the filename.

**Comment by oniony** [comment]
From my perspective this issue is now solved. Please reopen if you think otherwise or think there is further work to do.
