### ISSUE TITLE
Symbolic link handling

### ISSUE THREAD

**Issue by oniony** [oniony/TMSU#66]
Currently symbolic links are treated as regular files and not followed by TMSU, with the symbolic link itself being added to the database. However, I was wondering if it would be better if TMSU followed symbolic links to tag the target file instead?

Obviously there are a few considerations:
- When tagging a symbolic link, should the symbolic link path or the target file path be used to find the TMSU database? (I'm thinking that if one is tagging the target file it should be the target file's path.)
- What if the symbolic link is broken and the `--force` option is used? I suppose it could _still_ be the target file, only with blank size, fingerprint and modification times enterend into the database.
- There needs to be a way to tell TMSU to target the symbolic link itself _a la_ `-d`, `-P` or `--no-dereference` in the `cp` command.

Thoughts?

**Comment by 0ion9** [comment]
I agree with all your points; particularly the first point seems to describe the 'obvious correct behaviour' for 95%+ of cases.

The only possible wrinkle I can see here so far is if someone is already using 'overlapping' databases (where the same file is tagged both in a local db and the default db; or a local db and a db local to one of the parent/grandparent/... directories).
Personally I think overlapping dbs should be discouraged though, as that's just too confusing.

PS. I actually have a few such taggings. However, they are not intentional or desired, merely accidents caused mostly by symlinks.

**Comment by oniony** [comment]
Cool. I'll make this change in 0.7 then. Thanks.

**Comment by oniony** [comment]
Actually I"ve just realised my first two points are moot as the current working directory is used to find the database, not the location of the target file.

**Comment by oniony** [comment]
Still outstanding:

* `untag`
* `untagged`
* `status`
* `repair`

**Comment by xelxebar** [comment]
Would it be reasonable to also add an option to not follow symlinks by default for the various commands? I know that for my use case this would be really helpful.
