### ISSUE TITLE
Be more selective when creating links

### ISSUE THREAD

**Issue by DavidFromNL** [oniony/TMSU#87]
I tagged a few mp3 files. Gave them just a few tags: artist=..., lang(uage)=... and test. Every single file has a tag named artist and a tag named lang. That means I got the tree in [before.txt](https://github.com/oniony/TMSU/files/410860/before.txt) It's not the fact that they have a tag that is interesting, but the name=value combination that counts.

IMHO it does not make much sense to have links to files that have a symlink at the lowest level, because every single file I have tagged has a tag named artist. That means that artist/_.mp3 is just a list of all files. And so is artist/lang/_.mp3 :-) The mask artist/=Shakira/_.mp3 is useful, while /artist/=Shakira/lang/_.mp3 is the same as the previous list. Then again /artist/=Shakira/test/*.mp3 might be, because test is a tag without a value.

There are some alternatives I'd like better:
- Only list files which have a tag named artist but without a value at the lowest level
- When a tag has only entries with a value, don't show the lowest level at all
- Give tags a configurable option to do either of above or determine that that specific tag should never have links directly under it.

In a perfect situation, the tree would look like [after.txt](https://github.com/oniony/TMSU/files/410861/after.txt)

**Comment by oniony** [comment]
Without showing them at every level it becomes hard for the tool to know what you want and I believe the administrative burden of having to customise tags to specify whether you want files in the VFS to appear directly under them would be unbearable.

A competing tool, Tagsistant, deals with this problem by only resolving the list of files when instructed to do so with (I think) a `@` symbol. This is quite a nice solution but does require some knowledge on the part of the user and may be impossible to achieve in certain UI file choosers. Perhaps I could get the VFS to produce a directory called `files` at each level instead, and only when you step into that you get the actual file list? It does mean that anything enumerating the tree recursively will still encounter all of the files at every level, mind.

I'll have a think because I do agree it's not ideal having such a large number of files appearing as you step into the tree. It becomes unusable as the number of files increases.

**Comment by oniony** [comment]
Not quite what you were asking for, but I have made a change to the VFS to prevent files being listed under `tags` besides the tags directories. Instead you will find a `files` directory within which the set of files can be found.

Give it a whirl and let me know what you think. I'm considering it experimental at the moment.

**Comment by oniony** [comment]
I believe this solves the issue. Please reopen if not.
