### ISSUE TITLE
[Proposal] Non-Sequential IDs in SQLite3 Database

### ISSUE THREAD

**Issue by xelxebar** [oniony/TMSU#90]
## Proposal

Instead of using sequential integer `id`s (for the `file`, `tag` and `value` tables, *etc.*), using non-sequential (*e.g.* random) integers allows things like database merging.

## Use Case

My intended use case is to maintain a consistent tag database across multiple machines. Currently, I just naively sync the sqlite3 db file across machines. However, this is dangerous as local database copies can get out of sync if I'm not careful to always pull the latest version before adding a file.

Ideally, if my databases get out of sync, I want to be able to seamlessly merge the changes *a la git*. My initial attempt at a solution was to dump the tmsu database into an SQL file and maintain that in a git repo. That way I could merge the SQL files with git and then just rebuild the database from the merged version.

However, since IDs are sequential, merging these SQL files causes file/tag/value `id`s to collide. Since it doesn't seem that tmsu is making use of the sequential nature of current `id`s, changing these to random integers would allow use cases like my merging above without affecting the userside elsewhere.

**Comment by oniony** [comment]
Sorry I have not got back to you sooner, I have been on my annual holidays.

Thanks for the proposal. The reason I went with sequential integers is that I didn't want to make this component of the filenames in the VFS larger than it necessarily needed to be. In order to use a random (or hashing strategy) you would requires quite larger integers which means the filenames in the VFS would need to include quite lengthy UUIDs within them.

To do this I think it might be better to use alphanumeric identifiers instead, that way a UUID would be much shorter.

I'll have a think about this idea, especially with regards to the VFS as it may be there is another approach I could take to avoid name collisions within the VFS.

**Comment by 0ion9** [comment]
Hmm, I hadn't considered the possible effect this could have on VFS. If you used base64 to encode UUIDs in VFS filenames, that would be 11 characters, right?

@oniony : Not sure if you looked at [this](https://github.com/oniony/TMSU/pull/91) -- a pull request that seems to have "superceded" this issue. There is more discussion there.

**Comment by oniony** [comment]
Yes, I subsequently saw that, thanks.
