### ISSUE TITLE
Make available on Ubuntu

### ISSUE THREAD

**Issue by zaz** [oniony/TMSU#95]
I'm currently working on making this available on Ubuntu, and think I am most of the way there with the packaging. This issue is more to let you (and anyone else who may be interested) know than anything.

My work so far is at [zaz/tmsu-debian](https://github.com/zaz/tmsu-debian) (1000th commit BTW, whoot whoot!), and I hope to have a working PPA by tomorrow. If I'm tragically crushed by a falling piano before then, I hope someone will continue in my footsteps.

In the meantime, there were a few Lintian errors that you may want to address, but I don't think they're essential: Use of `/usr/sbin` (I believe this is deprecated in favor of `/usr/bin`), and missing manpages for binaries `tmsu-fs-merge`,  `tmsu-fs-mv`, and `tmsu-fs-rm`.

Does TMSU have any dependencies?

Is there anything else I should know?

Thanks for your time!

**Comment by oniony** [comment]
Hi,

That's great to hear. I've been hoping it would be packaged for Ubuntu for
some time.

I think somebody tried to get it packaged for Debian previously but there
were some licence notice issues upstream in the FUSE library that have
since been fixed.

Dependencies: only FUSE for running TMSU. Sqlite3 for compiling. And of
course Go and the bindings for these libraries as per the TMSU compilation
instructions.

Give me a shout if you hit any problems,
Paul

**Comment by zaz** [comment]
I've sent PR #96 with some changes to the Makefile necessary to build o `.deb`. The `debian` packaging itself can be found in [zaz/tmsu-debian:deb](https://github.com/zaz/tmsu-debian/tree/deb)

**Comment by zaz** [comment]
#### I have a working PPA!

TMSU can now be installed on Ubuntu 16.04 and above by running:

```
sudo add-apt-repository ppa:zazbrown
sudo apt-get update
sudo apt-get install tmsu
```

#### What next?

You can set up automatic deployment to the PPA simply by merging #96 and creating a `release` or `deploy` branch that tracks stable releases. Just let me know, and I'll update the Launchpad tracking URI.

I've created the team [TMSU](https://github.com/TMSU) to keep all the code in one place, and am happy to set you as owner of it, or delete it if you don't want it.

**Comment by oniony** [comment]
Hi, great news. Hope to merge the PR tomorrow.

Paul

**Comment by zaz** [comment]
Thanks for merging! Everything is now set up on Launchpad so that TMSU will automatically be pulled from github.com/TMSU/TMSU and released to a PPA. All you need to do is:

 1. Create a `stable` branch to track stable releases:  
    `git branch v0.6.1 stable`  
    `git push -u origin stable`
 2. [Transfer oniony/TMSU](https://github.com/oniony/TMSU/settings) to TMSU/TMSU.
 3. Feel free to [revoke my access to TMSU](https://github.com/orgs/TMSU/people/zaz), although it may be helpful if I retain admin access to `brand` and `debain`.

Issues, pull requests, and everything else will be transferred with the repo, and a redirect will be created.  
See: [About repository transfers.](https://help.github.com/articles/about-repository-transfers/)

**Comment by oniony** [comment]
OK, I was with you until this bit. Why is it necessary for me to transfer
my repo to this new 'organisation' you have created?

How will doing this affect other distro's packages that are built against
the current URL?

Why couldn't the Ubuntu package use the existing repo?

**Comment by zaz** [comment]
I set up a new PPA, `ppa:tmsu`, that tracks github.com/tmsu/tmsu. Sure, I can change it to track oniony/tmsu, I just thought it would be better to do it this way because:

 - It allows us to group the 3 repositories together, along with any future repositories
 - If the project changes hands in the future or you change your username, the GitHub TMSU URL will stay the same, and the Launchpad recipe will still work

If you revoke my admin rights on the organization, you'll have the exact same control over the project as you do now, but things will be more organized. I can't really see any downside to it.

If you don't want to do it that way though, I can update Launchpad to pull from oniony/tmsu.

If you want the stable PPA to work, you will need to create a stable branch though.

**Comment by oniony** [comment]
1. Yeah, I'm not moving the repo. Other packages are built upon its current
location. This is a file tagging app, not an institution.
2. I'm not fussed about the other repos. The graphics you created are
derivative works of my logo which I did not endorse. In fact, I never
licenced these files so they are technically in breach of copyright. :)
3. I don't mind creating a stable branch in which to put the tagged
versions.

On 13 Nov 2016 1:06 a.m., "Zaz Brown" <notifications@github.com> wrote:

I set up a new PPA, ppa:tmsu, that tracks github.com/tmsu/tmsu. Sure, I can
change it to track oniony/tmsu, I just thought it would be better to do it
this way because:

   - It allows us to group the 3 repositories together, along with any
   future repositories
   - If the project changes hands in the future or you change your
   username, the GitHub TMSU URL will stay the same, and the Launchpad recipe
   will still work

If you revoke my admin rights on the organization, you'll have the exact
same control over the project as you do now, but things will be more
organized. I can't really see any downside to it.

If you don't want to do it that way though, I can update Launchpad to pull
from oniony/tmsu.

If you want the stable PPA to work, you will need to create a stable branch
though.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/oniony/TMSU/issues/95#issuecomment-260159518>, or mute
the thread

**Comment by zaz** [comment]
1. No problem. Sorry for suggesting it. I've set up `ppa:tmsu` and `ppa:tmsu/daily` to track `oniony/TMSU`. PR #97 adds instructions to `README.md` for Ubuntu.
2. Sorry again. To be clear: I'm not trying to steal your logo, which is, as you said yourself, literally a pile of shit. The new logo is yours and you're obviously welcome to use it as you wish.
3. I just realized that **0.6.1** won't work directly because it doesn't have my changes to the Makefile, so it's actually best not to create a stable branch yet. I bootstrapped the stable PPA using a patched version of **0.6.1**, but it's setup so that when you create the branch **`stable`** it will track that. So you just need to remember to create **`stable`** the next time you release :)

At the moment `ppa:tmsu/daily` seems to be failing build because of the integration test `list_untagged`

**Comment by oniony** [comment]
OK, I'll merge the pull request later on today or tomorrow morning.

I want implying you were trying to steal the logo, merely that you were
changing the logo, and I don't want it changed. I intentionally didn't use
a luggage tag in its design. What is this new logo even for?

I can release a 0.6.2 to address this.

Cheers,
Paul

**Comment by zaz** [comment]
Sounds good!

I just thought a square logo that hints at what the program does might come in useful, especially if a GUI is ever made for TMSU. But if you don't want to use it, that's fine.

**Comment by oniony** [comment]
OK, I've reworked the installation instructions in 2487644.

**Comment by oniony** [comment]
Can you provide the details of the failing test? I have run the tests on both `master` and `v0.6` and they're passing fine here.

**Comment by oniony** [comment]
`Also, rather than releasing a v0.6.2 with just the Makefile changes, I might just as well push out v0.7.0 instead.

**Comment by zaz** [comment]
Weird. The tests are passing on my computer as well, and on Launchpad as of the latest commit. Everything is looking good now, but here is the [buildlog](https://launchpadlibrarian.net/293297165/buildlog_ubuntu-xenial-amd64.tmsu_0.6.1-0~970~ubuntu16.04.1_BUILDING.txt.gz) if you're still interested. The relevant line is:

    ./untagged/list_untagged [FAIL]

**Comment by littleD** [comment]
I have the same issue as zaz.

`2d1
< /tmp/tmsu/dir/file2
3a3
> /tmp/tmsu/dir/file2
./untagged/list_untagged [FAIL]`

**Comment by oniony** [comment]
Hmm, I'll take a look tomorrow on my train ride.

**Comment by oniony** [comment]
Looks like it's the ordering of the output. I'll pipe to sort for now but try to work this out properly tomorrow.

**Comment by oniony** [comment]
I was wondering why my checking didn't trigger a build but I see that the Ubuntu bpackage is still looking at https://github.com/TMSU rather than https://github.com/oniony/TMSU. Could you please update it to look at the official repository?

**Comment by zaz** [comment]
Where do you see this? Both the [stable](https://code.launchpad.net/~tmsu/tmsu/stable) and [daily](https://code.launchpad.net/~tmsu/tmsu/daily) branches on Launchpad are set up to track [github.com/oniony/TMSU](https://github.com/oniony/TMSU.git). I did notice I forgot to update the package description to reflect the change (fixed), but everything else seems to be pointing to the correct repo.

The [build recipe](https://code.launchpad.net/~tmsu/+recipe/tmsu-daily) did report build errors yesterday though.

**Comment by oniony** [comment]
I guess I must have misread the description to be an indication of the source, sorry about that.

The build appears to be failing because the build number is older than previously built:

    dpkg-genchanges: warning: the current version (0.6.1-0) is earlier than the previous one (0.6.1-1)

I guess that could be related to the change of URL?

I'm also a bit confused why the version is 0.6.1 when the version in `version.go` on `master` is 0.7.0. Shouldn't `tmsu-daily` be building `master`? Certainly the linked [`base source' shows](http://bazaar.launchpad.net/~tmsu/tmsu/daily/view/head:/src/github.com/oniony/TMSU/version/version.go) 0.7.0.

**Comment by zaz** [comment]
Oh man, what a pain. I'd switched the Debian package version back to `-0` in anticipation of you releasing 0.7.0 (0.7.0-0 supersedes 0.6.1-1), but it seems the version number is not updating.

I had assumed that `debuild` pulled the version number from the `VER` variable in the Makefile, but it seems that's not the case. I'm not very experienced with Debian packaging, but I believe it's pulling the version from [debian/changelog](https://github.com/TMSU/debian/blob/deb/changelog). If that's the case, we'll need some kind of webhook or Makefile code to update the changelog before building a the package.

I'm really not sure what the best way of fixing this is, but in the meantime, I've reverted to suffixing `-1` so the packages are building again.

**Comment by zaz** [comment]
Would you mind creating a "`stable`" branch so that the [Ubuntu PPA](https://code.launchpad.net/~tmsu/tmsu/stable) will resume creating builds for TMSU stable?

Having a stable branch may also simplify automated packaging on other distros such as Arch Linux.
